"""Initial migration

Revision ID: 774357505836
Revises: 
Create Date: 2025-02-26 01:03:43.385699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774357505836'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###